### ISSUE TITLE
Error while compiling, can anybody explain why it does this

### ISSUE THREAD

**Issue by RobDuthie** [upbeatlabs/drwattson#1]
C:\Users\DELLPR~1\AppData\Local\Temp\ccqzeRfx.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':

C:\Users\Dell Precision\Documents\Arduino\sketches\DRwattson_Getbytedata/DRwattson_Getbytedata.ino:46: undefined reference to `UpbeatLabs_MCP39F521::UpbeatLabs_MCP39F521()'

C:\Users\DELLPR~1\AppData\Local\Temp\ccqzeRfx.ltrans0.ltrans.o: In function `setup':

C:\Users\Dell Precision\Documents\Arduino\sketches\DRwattson_Getbytedata/DRwattson_Getbytedata.ino:56: undefined reference to `UpbeatLabs_MCP39F521::begin(unsigned char)'

C:\Users\DELLPR~1\AppData\Local\Temp\ccqzeRfx.ltrans0.ltrans.o: In function `loop':

C:\Users\Dell Precision\Documents\Arduino\sketches\DRwattson_Getbytedata/DRwattson_Getbytedata.ino:63: undefined reference to `UpbeatLabs_MCP39F521::read(UpbeatLabs_MCP39F521_Data*, UpbeatLabs_MCP39F521_AccumData*)'

C:\Users\Dell Precision\Documents\Arduino\sketches\DRwattson_Getbytedata/DRwattson_Getbytedata.ino:67: undefined reference to `UpbeatLabs_MCP39F521::convertRawData(UpbeatLabs_MCP39F521_Data*, UpbeatLabs_MCP39F521_FormattedData*)'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Pro or Pro Mini.

**Comment by sridharrajagopal** [comment]
Hi Rob, 

It looks like you haven't compiled the UpbeatLabs_MCP39F521.cpp and included it?

I also saw your other issue, where you said your compile issues were solved - can this be closed then?

-Sridhar

**Comment by sridharrajagopal** [comment]
Did you install UpbeatLabs_MCP39F521 in your standard Arduino library location? 

-Sridhar

**Comment by sridharrajagopal** [comment]
Closing because of no response. Assuming issue faced has been resolved. Please reopen if not.
