### ISSUE TITLE
Re bad compiling an new chip set MCP39F511

### ISSUE THREAD

**Issue by RobDuthie** [upbeatlabs/drwattson#2]
I have fixed the bad compile now by adding in the CPP file into the directory.
Now i have upgraded the chip set to a MCP39F511 which has different HEX command files to upload.
Were do i edits these in the .H or .CPP files?

**Comment by sridharrajagopal** [comment]
Hi Rob, 

Can you please elaborate? Are you trying to use the UpbeatLabs_MCP39F521 library with a MCP39F511 chip? MCP39F511 uses UART for communications. What HEX command files are you referring to? Can you post sample code or more details?

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment]
Closing because of no response. Assuming issue faced has been resolved. Please reopen if not.
