### ISSUE TITLE
Question: Curious about your calibration numbers ...

### ISSUE THREAD

**Issue by Humancell** [upbeatlabs/drwattson#3]
Hello,

Thank you so much for writing this library.  It has been very helpful in better understanding the Microchip MCP39F521.  And thank you for comment in the Microchip forums about your code and product.

In reviewing your code, I had a few questions I am hoping you do not mind explaining.

1. In your method UpbeatLabs_MCP39F521::resetCalibration() you have numerous values that are specific to your PCB and implementation.  I'm curious how you measured some of these to determine the proper values.  For example:

* data.calibrationPowerActive = 9920;
* data.calibrationPowerReactive = 1101;

What were you using to properly determine these components?

* Line #1229: retVal = writeGains(40386, 57724, 50987, 45458);

Once you determined these gain values, are you able to tweak them up or down slightly to further "fine tune" the readings obtained from the chip?

* Line #1234: retVal = writePhaseCompensation(208);

What did you use to determine this value, as it applies to your PCB?  Or what this autocalibrated based on the frequency that you provided?

Thank you in advance for your answers, and I again appreciate the effort that you put into this library!

**Comment by sridharrajagopal** [comment]
Hi Scott, 

Thanks for your message and your appreciation! :-)

As you alluded, the values I provided are specific to my PCB and implementation. MCP39F521 provides calibration routines (auto calibrate gains, auto calibrate reactive gains, and auto calibrate line frequency), as well as explains the calibration methodology in its datasheet. 

The above routines, which I've implemented in my library, help with the calibration wherein you don't have to set the gain values directly (or have to tweak them up or down). Once the calibration is done, the gains are set. In my reset calibration routine, I use these values to bring it back to "my" factory settings - i.e. for the Dr. Wattson board, which had been calibrated. MCP39F521 has another "factoryReset" command (which also I've implemented), which will bring the values back to its factory settings (which, of course, are not terribly interesting in this particular case, but the routine has been implemented for completeness). 

Hope that helps! 
Cheers, 
Sridhar
