### ISSUE TITLE
Checksum in issueAckNackCommand?

### ISSUE THREAD

**Issue by Humancell** [upbeatlabs/drwattson#4]
Hello,

In reviewing your code to learn more about interacting with tyhe MCP, I found a line of code that confused me:  [https://github.com/upbeatlabs/drwattson/blob/master/Arduino/UpbeatLabs_MCP39F521/UpbeatLabs_MCP39F521.cpp#L1373](https://github.com/upbeatlabs/drwattson/blob/master/Arduino/UpbeatLabs_MCP39F521/UpbeatLabs_MCP39F521.cpp#L1373)

`aucWriteDataBuf[3] = 0xa5 + 0x04 + command; // checksum`

I was expecting to see:

`aucWriteDataBuf[3] = (0xa5 + 0x04 + command) % 256;   // checksum`

Is this correct?  I thought the checksum had to be modulo 256?

**Comment by Humancell** [comment]
One additional question/comment ...

In your header you have:

```
enum response_code {
  RESPONSE_ACK = 0x06,
  RESPONSE_NACK = 0x07,
  RESPONSE_CSFAIL = 0x51
};
```
When I have been testing, I am seeing a NAK come back as 0x15?  Did you find the 0x07 somewhere in the documentation as another NAK response?

**Comment by sridharrajagopal** [comment]
Hi Scott, 

I'm delighted that you decided to pore over the code! Thanks! 

And yes, it should be modulo 256! I'm doing it everywhere else - this was an error. The reason why it was working without any issues is the nature of the ack/nack commands, where you don't really get back more than that. I'll update the code to do the modulo 256 for correctness. 

Thanks,
Sridhar


> Hello,
> 
> In reviewing your code to learn more about interacting with tyhe MCP, I found a line of code that confused me: https://github.com/upbeatlabs/drwattson/blob/master/Arduino/UpbeatLabs_MCP39F521/UpbeatLabs_MCP39F521.cpp#L1373
> 
> `aucWriteDataBuf[3] = 0xa5 + 0x04 + command; // checksum`
> 
> I was expecting to see:
> 
> `aucWriteDataBuf[3] = (0xa5 + 0x04 + command) % 256; // checksum`
> 
> Is this correct? I thought the checksum had to be modulo 256?

**Comment by sridharrajagopal** [comment]
I know that the datasheet lists 0x06 as the ack header. There's no mention of the nack value. Though I got it from somewhere, I haven't noted down the source, unfortunately, and I don't remember off the top of my head. If I do find the source, I'll update the comments accordingly. 

The NACK value is not used anyway, as only ACKs are acknowledged and the command marked successful. Speaking of RESPONSE_ACK, I'm not using that enum value in the code but hardcoded - I'll update that as well! Thanks for helping catch that! :-)

Cheers, 
Sridhar




> One additional question/comment ...
> 
> In your header you have:
> 
> ```
> enum response_code {
>   RESPONSE_ACK = 0x06,
>   RESPONSE_NACK = 0x07,
>   RESPONSE_CSFAIL = 0x51
> };
> ```
> When I have been testing, I am seeing a NAK come back as 0x15? Did you find the 0x07 somewhere in the documentation as another NAK response?

**Comment by Humancell** [comment]
Hello,

I'm hoping that some of this is helpful to you ... it's been a good learning lesson to read through how you dealt with this chip.  I've found the documentation and support ot be thin ... and delayed.

The NAK response of 0x15 I found on one of their related chip data sheets, and also in someone's comments in the forums.  And then, the other day, I started to get 0x15 responses when attempting to write a large block of registers.  I still don't know why ... but it just would not work.  :-(

Looking at your code, I saw you only write the smaller set of gain registers at once, and I tried this and it resolved my issue.

Thanks again for the great example of how to talk to this chip!  I'll have to look at how I might be able to use some of your devices ... they look nice!  It might be a good product to have on the bench as my reference!  :-)

I'll let you close this ticket!

**Comment by sridharrajagopal** [comment]
Hi, 

Yes, there are buffer size limitations on how much data you can send in one go, so I split it up into multiple smaller sections, both when reading and writing. Especially with the Arduino. 

The documentation is not bad - I had started off initially with an ST chip, and they are positively horrendous, and absolutely the worst support you can imagine! I could not even get their demo board to work! In comparison, Microchip's documentation is very very very good! :-) Their forum support is not that great, but their support with an SE is actually great. 

I just checked the forums today while researching the NAK codes and saw your posts - I've not had any major issues with reading/writing to it - hopefully splitting up the reads and writes resolved all of your issues. 

Calibration is not an easy thing, and the documentation could certainly be better in this regard, with a separate application note. 

If energy monitoring is one aspect of your solution and you're ok with a drop-in module, you can consider Dr. Wattson! Or if you want something more custom, I might be able to help as well. One difference with my approach over the demo board and schematic is that mine is an isolated design, so it could be used in a higher current scenario as well without any major modifications (other than CT and burden resistors, and the recalibration, of course! :-) ) 

I'll close the ticket after I've checked in my fix. I've done it, but I need to run my tests to verify it first before checking in.

Thanks for the catches!
-Sridhar

**Comment by sridharrajagopal** [comment]
I verified that NAK is indeed 0x15 on the MCP39F521 and fixed the enum. 

I've also checked in the other changes. 

Thanks for your catches!
