### ISSUE TITLE
Error compiling for ESP32 with `error: extra qualification`

### ISSUE THREAD

**Issue by whatnick** [upbeatlabs/drwattson#5]
Compiling for target ESP32 gives `error: extra qualification` on this line
```
int UpbeatLabs_MCP39F521::resetCalibration(calibration_config cc = CALIBRATION_CONFIG_4A );
```

According to [cppcheck](http://cppcheck.sourceforge.net/) this is not valid C++ construct and should be replaced with.
```
int resetCalibration(calibration_config cc = CALIBRATION_CONFIG_4A );
```

I will make a PR to fix this soon.

**Comment by sridharrajagopal** [comment]
Eek, a copy-paste error for sure!! Thanks much for finding and fixing it - I appreciate it! I'm surprised avr didn't complain!
