### ISSUE TITLE
Problem using MCP39F521

### ISSUE THREAD

**Issue by JoseMartiRhombio** [upbeatlabs/drwattson#7]
Hello,

I'm trying to use your library without modificate anything and the GetEnergyData.ino example with a MCP39F521 but I can't read data and in the terminal it sees "Error returned! 3"

**Comment by sridharrajagopal** [comment]
Which MCP39F521 board are you using? Dr. Wattson or something else? 

Also, which MCU/SBC are you using? Arduino, Raspberry Pi or something else? 

 "Error returned! 3" basically means it is having trouble with the I2C communication. Some things to watch out for are: 
1) Make sure cable is not loose
2) Make sure cable is not too long
3) Check your pull-up resistors - if you are using Dr. Wattson board, you don't need a pullup, but if you're using another board, make sure you have pullup resistors, and also make sure they are not too much. 

If it is not Arduino or Raspberry Pi, then the problem may be with the I2C library of the platform you are on. For example, someone had issues with Particle.io's board, and the CC3200 may need you to set the I2C speed lower. 

If you're using the Dr. Wattson board, you also need to configure the I2C address by soldering the solder jumpers appropriately, as mentioned in the user manual. 

If you can provide more details (as requested above), that would help in resolving the issue. 

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment]
Closing because I haven't heard back with additional information requested
