### ISSUE TITLE
Voltages and Currents Raw Data 

### ISSUE THREAD

**Issue by Amega328** [upbeatlabs/drwattson#8]
Hello,

Do I have access to the raw current and voltage sampled data from the  MCP39F521 chip ? 

Thanks.

**Comment by sridharrajagopal** [comment]
Hi, 

The MCP39F521 only publishes the computed RMS Current and Voltage. See the Register section 6 in the datasheet https://ww1.microchip.com/downloads/en/DeviceDoc/20005442A.pdf . 

Thanks,
Sridhar
